#!/bin/bash
epiphan="" #video zahvat
tt="" #video camera usb
plantronics="" #speakerphone
plantronics3200="" #speakerphone 3200
microsoft="" #microsoft web camera
delcom="" # pedali :-)
honeywell=""
zebra=""
digitalpersona="" #fingerprint
egalax="" #touchscreen
jabra=""
chicony=""
canoscan="" #scaner
canon="" #camera
biokey="" #fingerprint

usblist=$(usb-devices | grep 'Product=AV.io HDMI Video\|Product=USB2.0 Camera\|Product=Plantronics P610\|Product=Microsoft® LifeCam Studio(TM)\|Product=USB FS IO\|Product=HF500\|Product=ZTC ZD420-203dpi ZPL\|Product=U.are.U® 4500 Fingerprint Reader\|Product=eGalaxTouch EXC3147-2457-08.00.00|\Product=Plantronics Calisto 3200\|Product=Jabra SPEAK 410 USB\|Product=USB2.0 FHD Camera\|Product=CanoScan\|Product=Canon Digital Camera\|Product=Biokey 200 Fingerprint Scanner')
#check attached devices
epiphan=$(echo $usblist | grep 'Product=AV.io HDMI Video') #epiphan
tt=$(echo $usblist | grep 'Product=USB2.0 Camera')
microsoft=$(echo $usblist | grep Product='Microsoft® LifeCam Studio(TM)')
delcom=$(echo $usblist | grep 'Product=USB FS IO') # Pedali :-)
plantronics=$(echo $usblist | grep 'Product=Plantronics P610')
honeywell=$(echo $usblist | grep 'Product=HF500')
zebra=$(echo $usblist | grep 'Product=ZTC ZD420-203dpi ZPL')
digitalpersona=$(echo $usblist | grep 'Product=U.are.U® 4500 Fingerprint Reader')
egalax=$(echo $usblist | grep 'Product=eGalaxTouch EXC3147-2457-08.00.00')
plantronics3200=$(echo $usblist | grep 'Product=Plantronics Calisto 3200')
jabra=$(echo $usblist | grep 'Product=Jabra SPEAK 410 USB')
chicony=$(echo $usblist | grep 'Product=USB2.0 FHD Camera')
canoscan=$(echo $usblist | grep 'Product=CanoScan')
canon=$(echo $usblist | grep 'Product=Canon Digital Camera')
biokey=$(echo $usblist | grep 'Product=Biokey 200 Fingerprint Scanner')

if [[ "$biokey" == "$Null" ]] 
then 
biokey_st="0"
else
biokey_st="1"
fi

if [[ "$canon" == "$Null" ]] 
then 
canon_st="0"
else
canon_st="1"
fi

if [[ "$canoscan" == "$Null" ]] 
then 
canoscan_st="0"
else
canoscan_st="1"
fi

if [[ "$epiphan" == "$Null" ]] 
then 
epiphan_st="0"
else
epiphan_st="1"
fi

if [[ $tt == $Null ]] #Altamy camera
then
tt_st="0"
else
tt_st="1"
fi

if [[ $plantronics == $Null ]]
then
plantronics_st="0"
else
plantronics_st="1"
fi

if [[ $microsoft == $Null ]]
then
microsoft_st="0"
else
microsoft_st="1"
fi

if [[ "$delcom" == "$Null" ]] 
then 
delcom_st="0"
else
delcom_st="1"
fi

if [[ "$honeywell" == "$Null" ]] 
then 
honeywell_st="0"
else
honeywell_st="1"
fi

if [[ "$zebra" == "$Null" ]] 
then 
zebra_st="0"
else
zebra_st="1"
fi

if [[ "$digitalpersona" == "$Null" ]] 
then 
digitalpersona_st="0"
else
digitalpersona_st="1"
fi

if [[ "$egalax" == "$Null" ]] 
then 
egalax_st="0"
else
egalax_st="1"
fi

if [[ "$plantronics3200" == "$Null" ]] 
then 
plantronics3200_st="0"
else
plantronics3200_st="1"
fi

if [[ "$jabra" == "$Null" ]] 
then 
jabra_st="0"
else
jabra_st="1"
fi

if [[ "$chicony" == "$Null" ]] 
then 
chicony_st="0"
else
chicony_st="1"
fi

echo -e '{'
echo -e ' "data":['
echo -e '\t{'
echo -e '\t\t"{#USB.ZEBRA}":"'$zebra_st'",'
echo -e '\t\t"{#USB.ZEBRANAME}":"'ZTC ZD420-203dpi ZPL'",'
echo -e '\t\t"{#USB.DIGITALPERSONA}":"'$digitalpersona_st'",'
echo -e '\t\t"{#USB.DIGITALPERSONANAME}":"'U.are.U® 4500 Fingerprint Reader'",'
echo -e '\t\t"{#USB.EGALAX}":"'$egalax_st'",'
echo -e '\t\t"{#USB.EGALAXNAME}":"'eGalaxTouch EXC3147-2457-08.00.00'",'
echo -e '\t\t"{#USB.HONEYWELL}":"'$honeywell_st'",'
echo -e '\t\t"{#USB.HONEYWELLNAME}":"'HF500'",'
echo -e '\t\t"{#USB.JABRA}":"'$jabra_st'",'
echo -e '\t\t"{#USB.JABRANAME}":"'Jabra SPEAK 410 USB'",'
echo -e '\t\t"{#USB.EPIPHAN}":"'$epiphan_st'",'
echo -e '\t\t"{#USB.EPIPHANNAME}":"'AV.io HDMI Video'",'
echo -e '\t\t"{#USB.TT}":"'$tt_st'",'
echo -e '\t\t"{#USB.TTNAME}":"'USB2.0 Camera'",' #camera
echo -e '\t\t"{#USB.PLANTRONICS3200}":"'$plantronics3200_st'",'
echo -e '\t\t"{#USB.PLANTRONICSNAME3200}":"'Plantronics Calisto 3200'",'
echo -e '\t\t"{#USB.CHICONY}":"'$chicony_st'",'
echo -e '\t\t"{#USB.CHICONYNAME}":"'USB2.0 FHD Camera'",'
echo -e '\t\t"{#USB.CANOSCAN}":"'$canoscan_st'",'
echo -e '\t\t"{#USB.CANOSCANNAME}":"'CanoScan'",'
echo -e '\t\t"{#USB.CANON}":"'$canon_st'",'
echo -e '\t\t"{#USB.CANONNAME}":"'Canon Digital Camera'",'
echo -e '\t\t"{#USB.BIOKEY}":"'$biokey_st'",'
echo -e '\t\t"{#USB.BIOKEYNAME}":"'Biokey 200 Fingerprint Scanner'",'
echo -e '\t\t"{#USB.PLANTRONICS}":"'$plantronics_st'",'
echo -e '\t\t"{#USB.PLANTRONICSNAME}":"'Plantronics P610'",'
echo -e '\t\t"{#USB.DELCOM}":"'$delcom_st'",'
echo -e '\t\t"{#USB.DELCOMNAME}":"'USB FS IO'",' # Pedali :-)
echo -e '\t\t"{#USB.MICROSOFT}":"'$microsoft_st'",'
echo -e '\t\t"{#USB.MICROSOFTNAME}":"'Microsoft® LifeCam Studio'"'
echo -e '\t}'
echo ' ]'
echo '}'
